In [126]:
import numpy as np
my_list = [1,2,3]
my_list

[1, 2, 3]

In [127]:
type(my_list)

list

In [128]:
arr = np.array(my_list)

In [129]:
arr

array([1, 2, 3])

In [130]:
type(arr)

numpy.ndarray

In [131]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [132]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [133]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [135]:
np.zeros(3)

array([0., 0., 0.])

In [136]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [137]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [138]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

In [139]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [140]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [141]:
np.random.rand(5,5)

array([[0.2529516 , 0.45440826, 0.44982432, 0.69392338, 0.13242036],
       [0.43448297, 0.71860874, 0.6478779 , 0.25941462, 0.59800706],
       [0.96544328, 0.71508707, 0.62672879, 0.39208032, 0.3007469 ],
       [0.4292586 , 0.00673727, 0.22547726, 0.48831957, 0.03114151],
       [0.43783846, 0.13160509, 0.31085212, 0.08534358, 0.40691966]])

In [142]:
np.random.randn(3)##considers -ve values as well

array([-1.4545888 ,  1.25789401, -1.49655369])

In [143]:
np.random.randint(10,size=19)

array([7, 2, 7, 4, 0, 1, 8, 2, 8, 2, 4, 7, 6, 6, 1, 2, 9, 5, 2])

In [144]:
np.random.randint(0,10,size=(2,4))

array([[5, 3, 8, 0],
       [8, 7, 1, 7]])

In [145]:
arr = np.arange(25)

In [146]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [147]:
##Reshaping Array
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [148]:
randomarray = np.random.randint(0,50,10)

In [149]:
randomarray.sort()##mean() , max() , min() , sum()

In [150]:
randomarray.argmax() # argmin() to find max and min positions 

9

In [151]:
randomarray.shape

(10,)

In [152]:
randomarray.dtype

dtype('int32')

Numpy Array Indexing and Selection

In [153]:
arr =  np.arange(0,22,2)

In [154]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [155]:
arr[1:]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [156]:
arr[::2]

array([ 0,  4,  8, 12, 16, 20])

In [157]:
arr2 = [9,8,7,6,5,4,3,2,1]
arr2 = np.array(arr2)
arr2[0:3] = 100
arr2

array([100, 100, 100,   6,   5,   4,   3,   2,   1])

Indexing a 2D/Matrix Array

In [163]:
arr_2d = np.array([[5,10,15],[0,25,30],[35,40,45]])## generating random np.random.randint(0,46,size=(3,3))

In [164]:
arr_2d

array([[ 5, 10, 15],
       [ 0, 25, 30],
       [35, 40, 45]])

Double Bracket Format for accessing 2d array

In [168]:
arr_2d[0]

array([ 5, 10, 15])

In [178]:
extracted_data =  arr_2d[:,[0,1,2]]

In [215]:
extracted_data

array([[ 5, 10, 15],
       [ 0, 25, 30],
       [35, 40, 45]])

In [224]:
arr_2d[2:3,2:3]

array([[45]])

In [228]:
arr = [1,4,7,8]
arr = np.array(arr)
bool_arr = arr < 5
arr[bool_arr]

array([1, 4])

Numpy Operations
1 . Array with Array
2 . Array with scalars
3 . Universal Array Functions

In [229]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [230]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [236]:
arr/arr

C:\Users\visha\AppData\Local\Temp/ipykernel_13452/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [232]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [235]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [237]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [238]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [239]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [240]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [241]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

In [244]:
np.random.randint(0,8,size=(3,3))

array([[0, 7, 2],
       [6, 1, 7],
       [2, 7, 0]])

In [249]:
a = np.arange(0,9)

In [250]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])